project_id = "kzbaceuauzmndaighmtz"

[functions.create-checkout]
verify_jwt = false

[functions.get-stripe-price]
verify_jwt = false

[functions.payments-webhook]
verify_jwt = false

[functions.create-portal-session]
verify_jwt = false

[functions.get-affiliate-referrer]
verify_jwt = false

[functions.track-visit]
verify_jwt = false

[functions.improve-sentence]
verify_jwt = false

[functions.debate-turn]
verify_jwt = false

[functions.add-opponent-turn]
verify_jwt = false

[functions.parse-issue-document]
verify_jwt = false

[functions.debate-chat]
verify_jwt = false

[functions.get-translations]
verify_jwt = false
